/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;


import com.digitalpersona.onetouch.DPFPTemplate;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import monitor.Monitor;
import monitor.MonitorDAO;
import monitor.MonitorTableModel;
import util.LeitorBiometrico;
import util.Util;

/**
 *
 * @author Everton
 */
public class CadastroBiometria extends javax.swing.JFrame {

    MonitorDAO monitorDAO = new MonitorDAO();
    Monitor monitor = new Monitor();
    
    LeitorBiometrico digital = new LeitorBiometrico();
    
    DPFPTemplate templateDigital;
    
    public CadastroBiometria() {
        initComponents();
    }

    private void capturarDigitalMaoDireita() {
        if (jlMaoDireita.getText().equals("Capturada!")) {
            jlMaoDireita.setText("Não Capturada");
        }
        DPFPTemplate temp = digital.getTemplate(null, 1);
        byte[] b;
        try {
            b = temp.serialize();
            monitor.setDigitalDireita(b);
            jlMaoDireita.setText("Capturada!");
        } catch (Exception e) {
        }
    }

    private void capturarDigitalMaoEsquerda() {
        if (jlMaoEsquerda.getText().equals("Capturada!")) {
            jlMaoEsquerda.setText("Não Capturada");
        }
        DPFPTemplate temp = digital.getTemplate(null, 1);
        byte[] b;
        try {
            b = temp.serialize();
            monitor.setDigitalEsquerda(b);
            jlMaoEsquerda.setText("Capturada!");
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        lbMonitor = new javax.swing.JLabel();
        btnMaoDireita = new javax.swing.JButton();
        btnMaoEsquerda = new javax.swing.JButton();
        jlMaoDireita = new javax.swing.JLabel();
        jlMaoEsquerda = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnFoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MONITOR.:");

        btnAdicionar.setText("Add");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnMaoDireita.setText("Direita");
        btnMaoDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaoDireitaActionPerformed(evt);
            }
        });

        btnMaoEsquerda.setText("Esquerda");
        btnMaoEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaoEsquerdaActionPerformed(evt);
            }
        });

        jlMaoDireita.setText("Não capturado");

        jlMaoEsquerda.setText("Não capturado");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(lbMonitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdicionar)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlMaoDireita)
                            .addComponent(btnMaoEsquerda))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlMaoEsquerda)
                            .addComponent(btnMaoDireita))
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAdicionar)
                    .addComponent(lbMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMaoDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMaoEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlMaoDireita)
                            .addComponent(jlMaoEsquerda))
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        List<Monitor> lista = monitorDAO.listar();
        MonitorTableModel model = new MonitorTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(model, "Monitor");
        if (objetoRetorno != null) {
            monitor = monitorDAO.consultarObjetoId("id", objetoRetorno);
            lbMonitor.setText(monitor.getAluno().getNome());
            try {
                ImageIcon foto = new ImageIcon();
                foto.setImage(Util.byteToImage(monitor.getAluno().getFotoAluno()));
                btnFoto.setIcon(foto);
            } catch (Exception e) {
            }
            if (monitor.getDigitalDireita() != null) {
                jlMaoDireita.setText("Capturada!");
            }
            if (monitor.getDigitalEsquerda() != null) {
                jlMaoEsquerda.setText("Capturada!");
            }
            btnMaoDireita.setEnabled(true);
            btnMaoEsquerda.setEnabled(true);
        }    
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
            monitorDAO.salvar(monitor);
            
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnMaoDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaoDireitaActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Peça que por gentileza o professor(a) " + lbMonitor.getText() + "\n\n Escolha um dedo da mão DIREITA que ele gostaria de cadastrar\n\n"
        + "Após a escolha dele clique no OK abaixo para continuar o cadastro da digital");
        capturarDigitalMaoDireita();
    }//GEN-LAST:event_btnMaoDireitaActionPerformed

    private void btnMaoEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaoEsquerdaActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Peça que por gentileza o professor(a) " + lbMonitor.getText() + "\n\n Escolha um dedo da mão ESQUERDA que ele gostaria de cadastrar\n\n"
                + "Após a escolha dele clique no OK abaixo para continuar o cadastro da digital");
        capturarDigitalMaoEsquerda();
    }//GEN-LAST:event_btnMaoEsquerdaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroBiometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroBiometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroBiometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroBiometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroBiometria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnMaoDireita;
    private javax.swing.JButton btnMaoEsquerda;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlMaoDireita;
    private javax.swing.JLabel jlMaoEsquerda;
    private javax.swing.JLabel lbMonitor;
    // End of variables declaration//GEN-END:variables
}
