/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import curso.Curso;
import curso.CursoDAO;
import curso.CursoTableModel;
import disciplina.Disciplina;
import disciplina.DisciplinaDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import professor.Professor;
import professor.ProfessorDAO;
import professor.ProfessorTableModel;

/**
 *
 * @author Alisson
 */
public class CadastroDisciplina extends javax.swing.JFrame {
    
    Disciplina disciplina = new Disciplina();
    DisciplinaDAO disciplinaDAO = new DisciplinaDAO();
    
    CursoDAO cursoDAO = new CursoDAO();
    ProfessorDAO professorDAO = new ProfessorDAO();
    /**
     * Creates new form CadastroDisciplina
     */
    public CadastroDisciplina() {
        initComponents();
        
    }
    
    public void limparCampos(){
        tfNome.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        tfNome = new javax.swing.JTextField();
        lbCurso = new javax.swing.JLabel();
        lbProfessor = new javax.swing.JLabel();
        btnExcluirDisciplina = new javax.swing.JButton();
        btnSalvarDisciplina = new javax.swing.JButton();
        btnVoltarDisciplina = new javax.swing.JButton();
        btnPesquisarCurso = new javax.swing.JButton();
        btnPesquisarProfessor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaolupa.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 256, 40, 40));

        tfNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tfNome.setBorder(null);
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 258, 410, 35));

        lbCurso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbCurso.setText("Selecione um curso");
        getContentPane().add(lbCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 311, -1, -1));

        lbProfessor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbProfessor.setText("Selecione um professor");
        getContentPane().add(lbProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 357, -1, -1));

        btnExcluirDisciplina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoexcluirpequeno.png"))); // NOI18N
        btnExcluirDisciplina.setBorder(null);
        btnExcluirDisciplina.setBorderPainted(false);
        btnExcluirDisciplina.setContentAreaFilled(false);
        btnExcluirDisciplina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirDisciplinaActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluirDisciplina, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 436, 105, 35));

        btnSalvarDisciplina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaosalvarpequeno.png"))); // NOI18N
        btnSalvarDisciplina.setBorder(null);
        btnSalvarDisciplina.setBorderPainted(false);
        btnSalvarDisciplina.setContentAreaFilled(false);
        btnSalvarDisciplina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvarDisciplina.setPreferredSize(new java.awt.Dimension(159, 49));
        btnSalvarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDisciplinaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarDisciplina, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 434, 105, 35));

        btnVoltarDisciplina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaovoltarpequeno.png"))); // NOI18N
        btnVoltarDisciplina.setBorder(null);
        btnVoltarDisciplina.setBorderPainted(false);
        btnVoltarDisciplina.setContentAreaFilled(false);
        btnVoltarDisciplina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnVoltarDisciplina, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 438, -1, -1));

        btnPesquisarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaolupa.png"))); // NOI18N
        btnPesquisarCurso.setBorder(null);
        btnPesquisarCurso.setContentAreaFilled(false);
        btnPesquisarCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 302, 40, 40));

        btnPesquisarProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaolupa.png"))); // NOI18N
        btnPesquisarProfessor.setBorder(null);
        btnPesquisarProfessor.setContentAreaFilled(false);
        btnPesquisarProfessor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisarProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 349, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backgroundcadastrodisciplina.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirDisciplinaActionPerformed

    private void btnSalvarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDisciplinaActionPerformed
        disciplina.setNome(tfNome.getText());
        disciplinaDAO.salvar(disciplina);
        disciplina = new Disciplina();
        limparCampos();
    }//GEN-LAST:event_btnSalvarDisciplinaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnPesquisarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCursoActionPerformed
        List<Curso> lista = cursoDAO.listar();
        CursoTableModel model = new CursoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(model, "Curso");
        if(objetoRetorno != null){
            Curso curso = cursoDAO.consultarObjetoId("id", objetoRetorno);
            disciplina.setCurso(curso);
            lbCurso.setText(curso.getNome());
        }
    }//GEN-LAST:event_btnPesquisarCursoActionPerformed

    private void btnPesquisarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProfessorActionPerformed
        if(disciplina.getCurso() != null){
            List<Professor> lista = professorDAO.listar();
            List<Professor> listaFiltrada = new ArrayList<>();

            for(Professor professor : lista){
                if(professor.getCurso().getId() == disciplina.getCurso().getId()){
                    listaFiltrada.add(professor);
                }
            }
            ProfessorTableModel model = new ProfessorTableModel(listaFiltrada);

            Object objetoRetorno = PesquisaGenerica.exibeTela(model, "Professor");
            if(objetoRetorno != null){
                Professor professor = professorDAO.consultarObjetoId("id", objetoRetorno);
                disciplina.setProfessor(professor);
                lbProfessor.setText(professor.getNome());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um curso antes");
        }
    }//GEN-LAST:event_btnPesquisarProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDisciplina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirDisciplina;
    private javax.swing.JButton btnPesquisarCurso;
    private javax.swing.JButton btnPesquisarProfessor;
    private javax.swing.JButton btnSalvarDisciplina;
    private javax.swing.JButton btnVoltarDisciplina;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbCurso;
    private javax.swing.JLabel lbProfessor;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
