/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import curso.Curso;
import curso.CursoDAO;
import disciplina.Disciplina;
import disciplina.DisciplinaDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import monitor.Monitor;
import monitor.MonitorDAO;

/**
 *
 * @author Everton
 */
public class CadastroMonitor extends javax.swing.JFrame {
    
    Monitor monitor = new Monitor();
    MonitorDAO monitorDAO = new MonitorDAO();
    
    CursoDAO cursoDAO = new CursoDAO();
    DisciplinaDAO disciplinaDAO = new DisciplinaDAO();
    /**
     * Creates new form CadastroMonitor
     */
    public CadastroMonitor() {
        initComponents();
        
        for (Curso curso : cursoDAO.listarCurso()) {
            cbCurso.addItem(curso);
        }
    }

    public void limparCampos(){
        tfNome.setText("");
        tfMatricula.setText("");
        tfEmail.setText("");
        tfSemestre.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNome = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        tfMatricula = new javax.swing.JFormattedTextField();
        tfSemestre = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        cbCurso = new javax.swing.JComboBox<>();
        cbDisciplina = new javax.swing.JComboBox<>();
        rbInativo = new javax.swing.JRadioButton();
        rbAtivo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tfNome.setAlignmentX(10.0F);
        tfNome.setBorder(null);
        tfNome.setMargin(null);
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 245, 530, 30));

        tfEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tfEmail.setBorder(null);
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 297, 530, 30));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoexcluir.png"))); // NOI18N
        btnExcluir.setBorder(null);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 500, -1, -1));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaosalvar.png"))); // NOI18N
        btnSalvar.setBorder(null);
        btnSalvar.setBorderPainted(false);
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 495, -1, 50));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaolimpar.png"))); // NOI18N
        btnLimpar.setBorder(null);
        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 500, -1, -1));

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaovoltar.png"))); // NOI18N
        btnVoltar.setBorder(null);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 495, -1, -1));

        tfMatricula.setBorder(null);
        try {
            tfMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfMatricula.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tfMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(tfMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 349, 190, 30));

        tfSemestre.setBorder(null);
        try {
            tfSemestre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfSemestre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(tfSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 350, 190, 30));

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 445, 250, 40));

        cbCurso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbCurso.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cbCursoPopupMenuWillBecomeVisible(evt);
            }
        });
        cbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCursoActionPerformed(evt);
            }
        });
        getContentPane().add(cbCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 395, 250, 40));

        cbDisciplina.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(cbDisciplina, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 395, 310, 40));

        rbInativo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbInativo.setText("INATIVO");
        getContentPane().add(rbInativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 453, -1, -1));

        rbAtivo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbAtivo.setSelected(true);
        rbAtivo.setText("ATIVO");
        getContentPane().add(rbAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 453, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backgroundcadastromonitor.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(tfNome.getText().equals("") || tfMatricula.getText().equals("          ") || tfEmail.getText().equals("") || tfSemestre.getText().equals("     ")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente");
        }else{
            monitor.setNome(tfNome.getText());
            monitor.setMatricula(tfMatricula.getText());
            monitor.setEmail(tfEmail.getText());
            monitor.setSemestre(Integer.parseInt(tfSemestre.getText()));
            monitor.setCurso((Curso) cbCurso.getSelectedItem());
            limparCampos();
            monitorDAO.salvarMonitor(monitor);
            monitor = new Monitor();
            JOptionPane.showMessageDialog(null, "Monitor cadastrado com sucesso!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tfMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMatriculaActionPerformed

    private void cbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursoActionPerformed
//        List<Disciplina> listaDisciplina = new ArrayList<>();
//        for (Disciplina disciplina : disciplinaDAO.listarDisciplina()) {
//            if(disciplina.getCurso().equals((Curso)cbCurso.getSelectedItem())){
//                listaDisciplina.add(disciplina);
//            }
//        }
//        for (Disciplina disciplina : listaDisciplina) {
//            cbDisciplina.addItem(disciplina);
//        }

        for (Disciplina disciplina : disciplinaDAO.listarDisciplina()) {
            cbDisciplina.addItem(disciplina);
        }

    }//GEN-LAST:event_cbCursoActionPerformed

    private void cbCursoPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbCursoPopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCursoPopupMenuWillBecomeVisible

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MenuPrincipal frame = new MenuPrincipal();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMonitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<Curso> cbCurso;
    private javax.swing.JComboBox<Disciplina> cbDisciplina;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbAtivo;
    private javax.swing.JRadioButton rbInativo;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JFormattedTextField tfMatricula;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfSemestre;
    // End of variables declaration//GEN-END:variables
}
