/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telas;

import usuario.Usuario;

/**
 *
 * @author Everton
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private boolean seVisivelPainelCadastro;
    private boolean seVisivelPainelBiometria;
    private boolean seVisivelPainelRelatorio;
   
    public MenuPrincipal() {
        
        
        initComponents();
        panelBotaoCadastro.setVisible(false);
        //panelBotaoBiometria.setVisible(false);
        //panelBotaoRelatorio.setVisible(false);
        seVisivelPainelCadastro = false;
        seVisivelPainelBiometria = false;
        seVisivelPainelRelatorio = false;
    }

    MenuPrincipal(Usuario usuario) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastro = new javax.swing.JButton();
        btnBiometria = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        panelBotaoCadastro = new javax.swing.JPanel();
        btnCadastrarAlunoMenu3 = new javax.swing.JButton();
        btnCadastroProfessorMenu3 = new javax.swing.JButton();
        btnCadastroCursoMenu3 = new javax.swing.JButton();
        btnCadastrarMonitorMenu3 = new javax.swing.JButton();
        btnCadastrarMonitorMenu4 = new javax.swing.JButton();
        backgroundMenuPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaocadastro.png"))); // NOI18N
        btnCadastro.setBorder(null);
        btnCadastro.setBorderPainted(false);
        btnCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastro.setFocusPainted(false);
        btnCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastroMouseEntered(evt);
            }
        });
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 175, -1, -1));

        btnBiometria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaobiometria.png"))); // NOI18N
        btnBiometria.setBorder(null);
        btnBiometria.setBorderPainted(false);
        btnBiometria.setContentAreaFilled(false);
        btnBiometria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBiometria.setFocusPainted(false);
        btnBiometria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBiometriaMouseEntered(evt);
            }
        });
        btnBiometria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiometriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBiometria, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 175, -1, -1));

        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaorelatorio.png"))); // NOI18N
        btnRelatorio.setBorder(null);
        btnRelatorio.setBorderPainted(false);
        btnRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorio.setFocusPainted(false);
        btnRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseEntered(evt);
            }
        });
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 175, -1, -1));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaosair.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 503, -1, -1));

        panelBotaoCadastro.setBackground(new java.awt.Color(255, 255, 255));
        panelBotaoCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotaoCadastro.setPreferredSize(new java.awt.Dimension(148, 120));
        panelBotaoCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrarAlunoMenu3.setText("Cadastrar Professor");
        btnCadastrarAlunoMenu3.setBorder(null);
        btnCadastrarAlunoMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarAlunoMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAlunoMenu3ActionPerformed(evt);
            }
        });
        panelBotaoCadastro.add(btnCadastrarAlunoMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 147, 30));

        btnCadastroProfessorMenu3.setText("Cadastrar Monitor");
        btnCadastroProfessorMenu3.setBorder(null);
        btnCadastroProfessorMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastroProfessorMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroProfessorMenu3ActionPerformed(evt);
            }
        });
        panelBotaoCadastro.add(btnCadastroProfessorMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 147, 30));

        btnCadastroCursoMenu3.setText("Cadastrar Curso");
        btnCadastroCursoMenu3.setBorder(null);
        btnCadastroCursoMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastroCursoMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroCursoMenu3ActionPerformed(evt);
            }
        });
        panelBotaoCadastro.add(btnCadastroCursoMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 147, 30));

        btnCadastrarMonitorMenu3.setText("Cadastrar Disciplina");
        btnCadastrarMonitorMenu3.setBorder(null);
        btnCadastrarMonitorMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarMonitorMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMonitorMenu3ActionPerformed(evt);
            }
        });
        panelBotaoCadastro.add(btnCadastrarMonitorMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 147, 30));

        btnCadastrarMonitorMenu4.setText("Cadastrar Aluno");
        btnCadastrarMonitorMenu4.setBorder(null);
        btnCadastrarMonitorMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMonitorMenu4ActionPerformed(evt);
            }
        });
        panelBotaoCadastro.add(btnCadastrarMonitorMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 147, 30));

        getContentPane().add(panelBotaoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 149, 190));

        backgroundMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backgroundmenuprincipal.jpg"))); // NOI18N
        backgroundMenuPrincipal.setFocusCycleRoot(true);
        backgroundMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMenuPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backgroundMenuPrincipalMouseEntered(evt);
            }
        });
        getContentPane().add(backgroundMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        if(seVisivelPainelCadastro){
            panelBotaoCadastro.setVisible(false);
            seVisivelPainelCadastro = false;
        }else{
            panelBotaoCadastro.setVisible(true);
            seVisivelPainelCadastro = true;
        }
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void backgroundMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMenuPrincipalMouseClicked
       
        
        panelBotaoCadastro.setVisible(false);
        seVisivelPainelCadastro = false;
        btnBiometria.setVisible(false);
        seVisivelPainelBiometria = false;
        btnRelatorio.setVisible(false);
        seVisivelPainelRelatorio = false;
    }//GEN-LAST:event_backgroundMenuPrincipalMouseClicked

    private void btnCadastroProfessorMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroProfessorMenu3ActionPerformed
        CadastroMonitor frame = new CadastroMonitor();
        frame.setVisible(true);
    }//GEN-LAST:event_btnCadastroProfessorMenu3ActionPerformed

    private void btnBiometriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiometriaActionPerformed
        CadastroBiometria frame = new CadastroBiometria();
        frame.setVisible(true);
       
        
        /* if(seVisivelPainelBiometria){
            panelBotaoBiometria.setVisible(false);
            seVisivelPainelBiometria = false;
        } else{
            panelBotaoBiometria.setVisible(true);
            seVisivelPainelBiometria = true;
        }*/ 
    }//GEN-LAST:event_btnBiometriaActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        RelatorioPontoEletronico frame = new RelatorioPontoEletronico();
        frame.setVisible(true);

        
         /*if(seVisivelPainelRelatorio){
            panelBotaoRelatorio.setVisible(false);
            seVisivelPainelRelatorio = false;
        } else{
            panelBotaoRelatorio.setVisible(true);
            seVisivelPainelRelatorio = true;
        } */
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnCadastrarAlunoMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlunoMenu3ActionPerformed
        CadastroProfessor frame = new CadastroProfessor();
        frame.setVisible(true);
    }//GEN-LAST:event_btnCadastrarAlunoMenu3ActionPerformed

    private void btnCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseEntered
      
        
        panelBotaoCadastro.setVisible(true);
        //panelBotaoBiometria.setVisible(false);
        //panelBotaoRelatorio.setVisible(false); 
    }//GEN-LAST:event_btnCadastroMouseEntered

    private void btnBiometriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBiometriaMouseEntered
       
        
        //panelBotaoBiometria.setVisible(true);
        //panelBotaoCadastro.setVisible(false);
        //panelBotaoRelatorio.setVisible(false);
    }//GEN-LAST:event_btnBiometriaMouseEntered

    private void btnRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseEntered
      
        
        //panelBotaoRelatorio.setVisible(true);
       //panelBotaoCadastro.setVisible(false);
        //panelBotaoBiometria.setVisible(false);
    }//GEN-LAST:event_btnRelatorioMouseEntered

    private void backgroundMenuPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMenuPrincipalMouseEntered
       
        
       // panelBotaoRelatorio.setVisible(false);
        panelBotaoCadastro.setVisible(false);
        //panelBotaoBiometria.setVisible(false);
    }//GEN-LAST:event_backgroundMenuPrincipalMouseEntered

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnCadastrarMonitorMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMonitorMenu3ActionPerformed
        CadastroDisciplina frame = new CadastroDisciplina();
        frame.setVisible(true);
    }//GEN-LAST:event_btnCadastrarMonitorMenu3ActionPerformed

    private void btnCadastrarMonitorMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMonitorMenu4ActionPerformed
        CadastroAluno frame = new CadastroAluno();
        frame.setVisible(true);    }//GEN-LAST:event_btnCadastrarMonitorMenu4ActionPerformed

    private void btnCadastroCursoMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroCursoMenu3ActionPerformed
        CadastroCurso frame = new CadastroCurso();
        frame.setVisible(true);
    }//GEN-LAST:event_btnCadastroCursoMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundMenuPrincipal;
    private javax.swing.JButton btnBiometria;
    private javax.swing.JButton btnCadastrarAlunoMenu3;
    private javax.swing.JButton btnCadastrarMonitorMenu3;
    private javax.swing.JButton btnCadastrarMonitorMenu4;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCadastroCursoMenu3;
    private javax.swing.JButton btnCadastroProfessorMenu3;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton jButton11;
    private javax.swing.JPanel panelBotaoCadastro;
    // End of variables declaration//GEN-END:variables

}
