package telas;



import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import monitor.*;
import ponto.Ponto;
import ponto.PontoDAO;
import relatorio.Relatorio;

/**
 *
 * @author Alisson
 */
public class RelatorioPontoEletronico extends javax.swing.JFrame {
    
    Monitor monitor = new Monitor();
    MonitorDAO monitorDAO = new MonitorDAO();
    
    PontoDAO pontoDAO = new PontoDAO();
    /**
     * Creates new form RelatorioPontoEletronicoHiernate
     */
    public RelatorioPontoEletronico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tfDataInicio = new javax.swing.JFormattedTextField();
        tfDataFim = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        Layout = new javax.swing.JLabel();
        lbMonitor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 110, 30));

        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 100, 30));

        tfDataInicio.setBorder(null);
        try {
            tfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataInicio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(tfDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 130, 30));

        tfDataFim.setBorder(null);
        try {
            tfDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataFim.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(tfDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 130, 30));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 40, 40));

        Layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TelaGerarRelatorio.jpg"))); // NOI18N
        getContentPane().add(Layout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));
        getContentPane().add(lbMonitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 360, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String sql = "", texto = "";
        String novo = "", novoTexto = "";

        if (!tfDataInicio.getText().equals("  /  /    ") && !tfDataFim.getText().equals("  /  /    ")) {
            Date dataInicial = new Date();
            Date dataFinal = new Date();
            
            try {
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date data = format.parse(tfDataInicio.getText());
                dataInicial = data;
            } catch (ParseException e) {
                e.printStackTrace();
            }

            try {
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date data = format.parse(tfDataFim.getText());
                dataFinal = data;
            } catch (ParseException e) {
                e.printStackTrace();
            }
            
            List<Ponto> listaPontos = new ArrayList<>();
            
            if(monitor.getId() != 0){
                listaPontos = pontoDAO.consultarIntervaloPonto(monitor.getId(), dataInicial, dataFinal);
            }else{
                listaPontos = pontoDAO.consultarIntervaloPonto(dataInicial, dataFinal);
            }
//            for(Ponto ponto : listaPontos){
//                JOptionPane.showMessageDialog(null, ponto.getMonitor().getAluno().getNome() + ponto.getDataPonto());
//            }
            
            if(!listaPontos.isEmpty()){
                Relatorio.gerarRelatorio(listaPontos);
            }else{
                JOptionPane.showMessageDialog(null, "Nenhum registro de ponto foi encontrado");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "É obrigatório informar as duas datas!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Monitor> lista = monitorDAO.listar();
        MonitorTableModel model = new MonitorTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(model, "Monitor");
        if(objetoRetorno != null){
            monitor = monitorDAO.consultarObjetoId("id", objetoRetorno);
            lbMonitor.setText(monitor.getAluno().getNome());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioPontoEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioPontoEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioPontoEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioPontoEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioPontoEletronico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Layout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lbMonitor;
    private javax.swing.JFormattedTextField tfDataFim;
    private javax.swing.JFormattedTextField tfDataInicio;
    // End of variables declaration//GEN-END:variables
}
